// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsSql")>]
[<assembly: AssemblyProductAttribute("FsSql")>]
[<assembly: AssemblyCopyrightAttribute("Copyright Mauricio Scheffer © 2011-2015 & irium © 2018")>]
[<assembly: AssemblyDescriptionAttribute("Functional ADO.NET for F#")>]
[<assembly: AssemblyVersionAttribute("3.0.2")>]
[<assembly: AssemblyFileVersionAttribute("3.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsSql"
    let [<Literal>] AssemblyProduct = "FsSql"
    let [<Literal>] AssemblyCopyright = "Copyright Mauricio Scheffer © 2011-2015 & irium © 2018"
    let [<Literal>] AssemblyDescription = "Functional ADO.NET for F#"
    let [<Literal>] AssemblyVersion = "3.0.2"
    let [<Literal>] AssemblyFileVersion = "3.0.2"
